# ECE 396 - HHL Algorithm
#### Problem 1: Implement a 3x3 invertible but non-hermitian A in Qiskit

In [2]:
import numpy as np


We need to define a 3 x 3 invertible but non-hermitian A in Qiskit. That is, the following two qualities must hold:
$$AA^{-1} = A^{-1}A = I_n$$
$$A \neq A^{\dag}$$
If we restric ourselves to only real values, the matrix we can choose must then follow the two qualities: invertible and $A\neq A^T$.

One such matrix is the following:

$$A = \Bigg(\begin{matrix}
    1 & 0 & 0 \\
    0 & 1 & 0 \\
    0 & 1 & 1 
\end{matrix}\Bigg)$$


In [3]:
A = np.array([[1, 0, 0], [0, 1, 0], [0, 1, 1]])
print(A)

[[1 0 0]
 [0 1 0]
 [0 1 1]]


In [4]:
b = np.array([1, 2, 3])

Before I can use the HHL algorithm, we need to convert the non-hermitian matrix into a hermitian matrix form. We can complete this by performing the operation defined in the article. That is, define:
$$C = \Bigg(\begin{matrix}
    0 & A \\
    A^{\dag} & 0 \end{matrix}\Bigg)$$
C is now hermitian and can be used to solve  $C\cdot y = \Bigg[\begin{matrix} b  \\ 0 \end{matrix}\Bigg]$; where $y = \Bigg[\begin{matrix} 0  \\ x \end{matrix}\Bigg]$

In [5]:
from qiskit import Aer
from qiskit.algorithms.linear_solvers.hhl import HHL

backend = Aer.get_backend('aer_simulator')
hhl = HHL(quantum_instance=backend)



accurate_solution = hhl.solve(A, b)


/tmp/ipykernel_931172/524707097.py:5: DeprecationWarning: The HHL class is deprecated as of Qiskit Terra 0.22.0 and will be removed
        no sooner than 3 months after the release date.
        It is replaced by the tutorial at https://qiskit.org/textbook/ch-applications/hhl_tutorial.html"
        
  hhl = HHL(quantum_instance=backend)


QiskitError: 'The number of rows of the isometry is not a non negative power of 2.'